# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ vars.DOCKERHUB_USERNAME }}/fp-plus-docker:${{ github.sha }} --push .
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'fp-plus-react-terraform'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: '${{ vars.DOCKERHUB_USERNAME }}/fp-plus-docker:${{ github.sha }}'